export const STATES = [
  { name: 'Aguascalientes', abbr: 'AGS' },
  { name: 'Baja California', abbr: 'BCN' },
  { name: 'Baja California Sur', abbr: 'BCS' },
  { name: 'Campeche', abbr: 'CAM' },
  { name: 'Chiapas', abbr: 'CHIS' },
  { name: 'Chihuahua', abbr: 'CHP' },
  { name: 'Coahuila', abbr: 'COAH' },
  { name: 'Colima', abbr: 'CHH' },
  { name: 'Durango', abbr: 'DGO' },
  { name: 'Guanajuato', abbr: 'GTO' },
  { name: 'Guerrero', abbr: 'GRO' },
  { name: 'Hidalgo', abbr: 'HGO' },
  { name: 'Jalisco', abbr: 'JAL' },
  { name: 'México', abbr: 'MEX' },
  { name: 'Michoacán', abbr: 'MICH' },
  { name: 'Morelos', abbr: 'MOR' },
  { name: 'Nayarit', abbr: 'NAY' },
  { name: 'Nuevo León', abbr: 'NL' },
  { name: 'Oaxaca', abbr: 'OAX' },
  { name: 'Puebla', abbr: 'PUE' },
  { name: 'Querétaro', abbr: 'QRO' },
  { name: 'Quintana Roo', abbr: 'QR' },
  { name: 'San Luis Potosí', abbr: 'SLP' },
  { name: 'Sinaloa', abbr: 'SIN' },
  { name: 'Sonora', abbr: 'SON' },
  { name: 'Tabasco', abbr: 'TAB' },
  { name: 'Tamaulipas', abbr: 'TAM' },
  { name: 'Tlaxcala', abbr: 'TLAX' },
  { name: 'Veracruz', abbr: 'VER' },
  { name: 'Yucatán', abbr: 'YUC' },
  { name: 'Zacatecas', abbr: 'ZAC' },
]
